### ISSUE TITLE
GH page typo

### ISSUE THREAD

**Issue by stephan281094** [Elhebert/vue-fineuploader-dropzone#16]
Hi there!

When opening the [demo](https://elhebert.github.io/vue-fineuploader-dropzone/), I noticed that the Github link at the bottom contains a typo. It links to https://github.com/Elhberet/vue-fineuploader-dropzone, while it should link to https://github.com/Elhebert/vue-fineuploader-dropzone.

Keep up the good work!

**Comment by Elhebert** [comment]
Yup indeed, thx. But this repo is not supported anymore ^^

You can go check this one: https://github.com/FineUploader/vue-fineuploader

**Comment by stephan281094** [comment]
Oh, okay. Good to know!
